# Generated by Django 3.1.4 on 2020-12-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.CharField(max_length=16, verbose_name='talentid')),
                ('mail', models.CharField(max_length=128, verbose_name='mail')),
            ],
        ),
    ]
