# Generated by Django 3.1.4 on 2020-12-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer', '0003_auto_20201214_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickfn',
            field=models.CharField(default='', max_length=512, verbose_name='Fortnite_nickname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='epicid',
            field=models.CharField(default=0, max_length=128, verbose_name='epicid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='overwatchname',
            field=models.CharField(default=0, max_length=128, verbose_name='overwatch_name'),
        ),
    ]
