# Generated by Django 3.1.4 on 2020-12-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer', '0004_auto_20201215_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.CharField(default='', max_length=512, verbose_name='Fortnite_nickname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickfn',
            field=models.CharField(default='', max_length=128, verbose_name='Fortnite_nickname'),
        ),
    ]
