# Generated by Django 3.1.4 on 2020-12-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer', '0005_auto_20201215_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='epicid',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='epicid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.CharField(blank=True, default='https://st2.depositphotos.com/5266903/8135/v/600/depositphotos_81358350-stock-illustration-client-flat-icon.jpg', max_length=512, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickfn',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Fortnite_nickname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='overwatchname',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='overwatch_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teamplay',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='TeamPlay'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teamplayfn',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='TeamPlay_Fortnite'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teamplayow',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='TeamPlay_Overwatch'),
        ),
    ]
