# Generated by Django 3.1.4 on 2020-12-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamer', '0006_auto_20201217_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
    ]
