# Generated by Django 3.1.4 on 2020-12-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer', '0007_remove_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
